export type EmojiItem = {
  emoji: string
  keywords: string
}

export type EmojiGroup = {
  id: string
  label: string
  items: EmojiItem[]
}

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    id: "faces",
    label: "פנים",
    items: [
      { emoji: "😀", keywords: "שמח חיוך" },
      { emoji: "😁", keywords: "חיוך שיניים" },
      { emoji: "😂", keywords: "צחוק דמעות" },
      { emoji: "🤣", keywords: "מצחיק צחוק" },
      { emoji: "😊", keywords: "נעים חיוך" },
      { emoji: "😇", keywords: "מלאך" },
      { emoji: "🥰", keywords: "אהבה לב" },
      { emoji: "😍", keywords: "מאוהב עיניים" },
      { emoji: "🤩", keywords: "וואו מתלהב" },
      { emoji: "😘", keywords: "נשיקה" },
      { emoji: "😋", keywords: "טעים" },
      { emoji: "😜", keywords: "שובב לשון" },
      { emoji: "🤪", keywords: "משוגע כיף" },
      { emoji: "🤗", keywords: "חיבוק" },
      { emoji: "🤔", keywords: "חושב" },
      { emoji: "😌", keywords: "רגוע" },
      { emoji: "😴", keywords: "שינה עייף" },
      { emoji: "🥱", keywords: "מפהק עייף" },
      { emoji: "😎", keywords: "מגניב משקפיים" },
      { emoji: "🥳", keywords: "מסיבה יום הולדת" },
      { emoji: "😮", keywords: "מופתע" },
      { emoji: "😢", keywords: "עצוב בכי" },
      { emoji: "😤", keywords: "כועס" },
      { emoji: "🤒", keywords: "חולה" },
      { emoji: "🤠", keywords: "כובע" },
      { emoji: "👋", keywords: "שלום ביי" },
    ],
  },
  {
    id: "learn",
    label: "לימודים",
    items: [
      { emoji: "📚", keywords: "ספרים לימוד" },
      { emoji: "📖", keywords: "קריאה ספר" },
      { emoji: "✏️", keywords: "עיפרון כתיבה שיעורים" },
      { emoji: "📝", keywords: "פתק כתיבה" },
      { emoji: "📓", keywords: "מחברת" },
      { emoji: "🖊️", keywords: "עט" },
      { emoji: "🖍️", keywords: "צבע פסטל" },
      { emoji: "🔢", keywords: "חשבון מספרים" },
      { emoji: "🔤", keywords: "אותיות א ב" },
      { emoji: "🎓", keywords: "לימודים סיום" },
      { emoji: "🧠", keywords: "מוח חשיבה" },
      { emoji: "🔍", keywords: "חיפוש זכוכית" },
      { emoji: "📐", keywords: "הנדסה משולש" },
      { emoji: "📏", keywords: "סרגל" },
      { emoji: "🔬", keywords: "מדע מיקרוסקופ" },
      { emoji: "🧪", keywords: "ניסוי מדע" },
      { emoji: "🧮", keywords: "חשבון חשבונייה" },
      { emoji: "🗺️", keywords: "מפה גיאוגרפיה" },
      { emoji: "💡", keywords: "רעיון אור" },
      { emoji: "📌", keywords: "נעץ תזכורת" },
    ],
  },
  {
    id: "play",
    label: "משחק",
    items: [
      { emoji: "⚽", keywords: "כדורגל כדור משחק" },
      { emoji: "🏀", keywords: "כדורסל" },
      { emoji: "🏈", keywords: "פוטבול" },
      { emoji: "⚾", keywords: "בייסבול" },
      { emoji: "🎾", keywords: "טניס" },
      { emoji: "🏐", keywords: "כדורעף" },
      { emoji: "🎱", keywords: "כדור ביליארד" },
      { emoji: "🏓", keywords: "פינג פונג" },
      { emoji: "🏸", keywords: "בדמינטון" },
      { emoji: "⛳", keywords: "גולף" },
      { emoji: "🎯", keywords: "מטרה" },
      { emoji: "🎮", keywords: "משחק מסך מחשב סוני פלייסטיישן" },
      { emoji: "📱", keywords: "אייפון טלפון נייד" },
      { emoji: "💻", keywords: "טאבלט מחשב אייפד" },
      { emoji: "🕹️", keywords: "ג'ויסטיק משחק" },
      { emoji: "🎲", keywords: "קובייה" },
      { emoji: "🧩", keywords: "פאזל" },
      { emoji: "🧸", keywords: "בובה דוב" },
      { emoji: "🪁", keywords: "עפיפון" },
      { emoji: "🎪", keywords: "קרקס" },
      { emoji: "🎨", keywords: "ציור צבעים" },
      { emoji: "🎭", keywords: "תיאטרון מסכה" },
      { emoji: "🎳", keywords: "באולינג" },
      { emoji: "🥊", keywords: "אגרוף" },
      { emoji: "🏆", keywords: "גביע פרס" },
      { emoji: "🥇", keywords: "מדליה זהב" },
    ],
  },
  {
    id: "sport",
    label: "ספורט",
    items: [
      { emoji: "🏃", keywords: "ריצה" },
      { emoji: "🚴", keywords: "אופניים" },
      { emoji: "🏊", keywords: "שחייה בריכה" },
      { emoji: "🤸", keywords: "התעמלות סלטה" },
      { emoji: "🧘", keywords: "יוגה רגיעה" },
      { emoji: "⛹️", keywords: "כדור" },
      { emoji: "🏄", keywords: "גלישה ים" },
      { emoji: "🧗", keywords: "טיפוס" },
      { emoji: "🤾", keywords: "כדוריד" },
      { emoji: "🏇", keywords: "סוס רכיבה" },
      { emoji: "🛹", keywords: "סקייטבורד" },
      { emoji: "⛸️", keywords: "החלקה קרח" },
      { emoji: "⛷️", keywords: "סקי" },
      { emoji: "🤸‍♀️", keywords: "התעמלות" },
    ],
  },
  {
    id: "food",
    label: "אוכל",
    items: [
      { emoji: "🍎", keywords: "תפוח פרי" },
      { emoji: "🍌", keywords: "בננה" },
      { emoji: "🍇", keywords: "ענבים" },
      { emoji: "🍓", keywords: "תות" },
      { emoji: "🍉", keywords: "אבטיח" },
      { emoji: "🍑", keywords: "אפרסק" },
      { emoji: "🍒", keywords: "דובדבן" },
      { emoji: "🥝", keywords: "קיווי" },
      { emoji: "🥕", keywords: "גזר" },
      { emoji: "🥦", keywords: "ברוקולי" },
      { emoji: "🌽", keywords: "תירס" },
      { emoji: "🍞", keywords: "לחם" },
      { emoji: "🥐", keywords: "קרואסון" },
      { emoji: "🧀", keywords: "גבינה" },
      { emoji: "🍳", keywords: "ביצה חביתה" },
      { emoji: "🥞", keywords: "פנקייק" },
      { emoji: "🍗", keywords: "עוף" },
      { emoji: "🍔", keywords: "המבורגר" },
      { emoji: "🍟", keywords: "צ'יפס" },
      { emoji: "🍕", keywords: "פיצה" },
      { emoji: "🌮", keywords: "טאקו" },
      { emoji: "🍜", keywords: "מרק אטריות" },
      { emoji: "🍣", keywords: "סושי" },
      { emoji: "🍩", keywords: "סופגנייה" },
      { emoji: "🍪", keywords: "עוגייה" },
      { emoji: "🎂", keywords: "עוגה יום הולדת" },
      { emoji: "🍦", keywords: "גלידה" },
      { emoji: "🥛", keywords: "חלב" },
      { emoji: "🥤", keywords: "שתייה כוס" },
      { emoji: "🧃", keywords: "מיץ" },
    ],
  },
  {
    id: "animals",
    label: "חיות",
    items: [
      { emoji: "🐶", keywords: "כלב" },
      { emoji: "🐱", keywords: "חתול" },
      { emoji: "🐭", keywords: "עכבר" },
      { emoji: "🐹", keywords: "אוגר" },
      { emoji: "🐰", keywords: "ארנב" },
      { emoji: "🦊", keywords: "שועל" },
      { emoji: "🐻", keywords: "דוב" },
      { emoji: "🐼", keywords: "פנדה" },
      { emoji: "🐨", keywords: "קואלה" },
      { emoji: "🐯", keywords: "נמר" },
      { emoji: "🦁", keywords: "אריה" },
      { emoji: "🐮", keywords: "פרה" },
      { emoji: "🐷", keywords: "חזיר" },
      { emoji: "🐸", keywords: "צפרדע" },
      { emoji: "🐵", keywords: "קוף" },
      { emoji: "🐔", keywords: "תרנגול" },
      { emoji: "🐧", keywords: "פינגווין" },
      { emoji: "🐦", keywords: "ציפור" },
      { emoji: "🦄", keywords: "חד קרן" },
      { emoji: "🐝", keywords: "דבורה" },
      { emoji: "🦋", keywords: "פרפר" },
      { emoji: "🐢", keywords: "צב" },
      { emoji: "🐠", keywords: "דג" },
      { emoji: "🦉", keywords: "ינשוף" },
    ],
  },
  {
    id: "day",
    label: "יום ובית",
    items: [
      { emoji: "☀️", keywords: "שמש בוקר" },
      { emoji: "🌤️", keywords: "מזג אוויר" },
      { emoji: "🌈", keywords: "קשת" },
      { emoji: "🌙", keywords: "ירח לילה שינה" },
      { emoji: "⭐", keywords: "כוכב" },
      { emoji: "🌟", keywords: "כוכב זוהר" },
      { emoji: "✨", keywords: "נצנוץ" },
      { emoji: "🏠", keywords: "בית" },
      { emoji: "🛏️", keywords: "מיטה שינה" },
      { emoji: "🚿", keywords: "מקלחת" },
      { emoji: "🛁", keywords: "אמבטיה" },
      { emoji: "🪥", keywords: "מברשת שיניים" },
      { emoji: "🦷", keywords: "שיניים" },
      { emoji: "👕", keywords: "בגדים חולצה" },
      { emoji: "👖", keywords: "מכנסיים" },
      { emoji: "👗", keywords: "שמלה" },
      { emoji: "👟", keywords: "נעליים" },
      { emoji: "🧦", keywords: "גרביים" },
      { emoji: "🎒", keywords: "תיק בית ספר" },
      { emoji: "🚌", keywords: "אוטובוס" },
      { emoji: "🏫", keywords: "בית ספר" },
      { emoji: "🌳", keywords: "עץ פארק" },
      { emoji: "🌸", keywords: "פרח" },
      { emoji: "🌻", keywords: "חמניה" },
      { emoji: "🌼", keywords: "פרח צהוב" },
      { emoji: "🍀", keywords: "תלתן מזל" },
      { emoji: "🌿", keywords: "עלה" },
      { emoji: "🌊", keywords: "ים גלים" },
      { emoji: "⏰", keywords: "שעון זמן" },
      { emoji: "🧹", keywords: "ניקיון מטאטא" },
      { emoji: "🧺", keywords: "כביסה סל" },
      { emoji: "🧼", keywords: "סבון" },
      { emoji: "🎁", keywords: "מתנה" },
      { emoji: "🎈", keywords: "בלון" },
    ],
  },
  {
    id: "music",
    label: "מוזיקה",
    items: [
      { emoji: "🎵", keywords: "מוזיקה תו" },
      { emoji: "🎶", keywords: "שיר" },
      { emoji: "🎤", keywords: "שירה מיקרופון" },
      { emoji: "🎧", keywords: "אוזניות" },
      { emoji: "🎹", keywords: "פסנתר" },
      { emoji: "🎸", keywords: "גיטרה" },
      { emoji: "🥁", keywords: "תופים" },
      { emoji: "🎻", keywords: "כינור" },
      { emoji: "🎺", keywords: "חצוצרה" },
      { emoji: "🎬", keywords: "סרט קולנוע" },
      { emoji: "📷", keywords: "מצלמה" },
      { emoji: "📺", keywords: "טלוויזיה מסך" },
    ],
  },
  {
    id: "hearts",
    label: "לבבות",
    items: [
      { emoji: "❤️", keywords: "לב אהבה" },
      { emoji: "💛", keywords: "לב צהוב" },
      { emoji: "💚", keywords: "לב ירוק" },
      { emoji: "💙", keywords: "לב כחול" },
      { emoji: "💜", keywords: "לב סגול" },
      { emoji: "🩷", keywords: "לב ורוד" },
      { emoji: "🧡", keywords: "לב כתום" },
      { emoji: "👍", keywords: "כל הכבוד" },
      { emoji: "👏", keywords: "מחיאות כפיים" },
      { emoji: "💪", keywords: "חזק כוח" },
      { emoji: "🙏", keywords: "תודה" },
      { emoji: "💤", keywords: "שינה נחירה" },
    ],
  },
]

export const EMOJI_COUNT = EMOJI_GROUPS.reduce(
  (total, group) => total + group.items.length,
  0
)
